### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by Adaurg** [hauleth/dotfiles#2]
Hello,

Thanks for your work
When i run ./install i have this error :
./install: line 45: -r: command not found

I'm on linux lite 2.2/32bits and i have your requirements
Please can you help me ?
Thanks

**Comment by hauleth** [comment]
I haven't updated README in some time and it needs review. For now there is fixed `./install` script that will provide info if there is no `jq` available.

Also `./install` script still doesn't link all config files. For now it is replacement for `git submodule` system and only fetches needed files. I will fix that when I will have some time to spare.

**Comment by Adaurg** [comment]
./install script working well with jq installed :+1: 
Big thanks :)
